spring.application.name=cashu-demo-db
spring.datasource.url=jdbc:postgresql://localhost:5432/cashu_wallet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.hostname=localhost
server.port=6666